report:
  title: "The effect of magnesium supplementation on sleep quality: evidence from my fitbit"
  author: "Peter Richens"
  design: "A blinded randomised trial was conducted on 1 adult male (me). The patient's sleep episodes where randomly allocated into the magnesium or the control group and received 400 mg magnesium citrate or an over-the-counter multivitamin supplement. Sleep activity was tracked by the patient's Fitbit device."
  source: "https://github.com/peterjrichens/personal-rct"
  keywords:
    - "magnesium"
    - "sleep"
    - "magnesium supplementation"
    - "insomnia"
    - "activity trackers"
    - "fitbit"
  related_studies: "https://www.connectedpapers.com/main/042fc87490256d934f2b025b6ca6c6115be73404"

data:
  source: "fitbit"
  path: "data/MyFitbitData/PeterRichens"
  start_date: "2021-03-11"
  end_date: "2021-05-23"

treatment:
  dates:
    magnesium:
      - "2021-04-11"
      - "2021-04-13"
      - "2021-04-15"
      - "2021-04-17"
      - "2021-04-19"
      - "2021-04-23"
      - "2021-04-25"
      - "2021-04-27"
      - "2021-04-29"
      - "2021-05-03"
      - "2021-05-05"
      - "2021-05-09"
      - "2021-05-11"
      - "2021-05-13"
      - "2021-05-15"
      - "2021-05-17"
      - "2021-05-19"
      - "2021-05-21"
      - "2021-05-19"
      - "2021-05-21"
    multivitamin:
      - "2021-04-12"
      - "2021-04-14"
      - "2021-04-16"
      - "2021-04-18"
      - "2021-04-20"
      - "2021-04-22"
      - "2021-04-24"
      - "2021-04-26"
      - "2021-04-28"
      - "2021-04-30"
      - "2021-05-02"
      - "2021-05-04"
      - "2021-05-06"
      - "2021-05-08"
      - "2021-05-10"
      - "2021-05-12"
      - "2021-05-14"
      - "2021-05-16"
      - "2021-05-18"
      - "2021-05-20"
      - "2021-05-18"
      - "2021-05-20"
      - "2021-05-22"
  exclude_dates:
    - "2021-04-21"
    - "2021-05-01"
    - "2021-05-07"
  target: "magnesium"
  reference: "multivitamin"


model:
  dependent_variables:
    - "composite_sleep_score"
    - "total_sleep_duration"
    - "rem_sleep_duration"
    - "deep_sleep_duration"
  control_variables:
    - "day_of_week"
    - "sleep_start_time"
    - "steps"
    - "calories"
