dependencies:
  - python=3.7.5
  - pip=19.3.1
  - pip:
    - jupyter==1.0.0
    - papermill==2.3.3
    - pandas==1.0.0
    - numpy==1.18.1
    - statsmodels==0.12.1
    - matplotlib==3.1.3
    - seaborn==0.10.0
    - black==19.10b0
    - nb-black==1.0.7
    - glob2==0.7
